### ISSUE TITLE
Not sure I have permissions to create a branch in this repo?

### ISSUE THREAD

**Issue by EricKeenan** [ICESAT-2HackWeek/Snowblower#1]
I made a text file (project_ideas.txt) with projects ideas, to do items, and problems that I would like to push to github. I tried to create a new branch called "Eric", but when I push (git push origin Eric), I get the following error: 

"
jovyan@jupyter-erickeenan:~/Snowblower$ git push origin Eric
Username for 'https://github.com': EricKeenan
Password for 'https://EricKeenan@github.com':
remote: Permission to ICESAT-2HackWeek/Snowblower.git denied to EricKeenan.
fatal: unable to access 'https://github.com/ICESAT-2HackWeek/Snowblower.git/': The requested URL returned error: 403

"

When I run git status I get the following:

"

On branch Eric
nothing to commit, working tree clean 

"

**Comment by jeffreymei** [comment]
That's weird. Can you push it to master? (Git checkout master, then git add project_ideas.txt, then git push). I wonder if it is because of the way the jupyter is set up; you can also try cloning to a local directory and pushing from that (this worked for me)

**Comment by EricKeenan** [comment]
Same error when pushing to master 👎 . I'll get some help tomorrow, and report back here on the solution.

**Comment by jeffreymei** [comment]
Oh, just realised you were not on the collaborator list. I just added you, try it again?

**Comment by jeffreymei** [comment]
Also, when you push from your branch, you should use git push -u origin Eric. This ensures your branch is linked to the right upstream repository, technically you only need it for your first commit and then git will remember.

**Comment by jeffreymei** [comment]
Yeah, I just tried pushing from pangeo.io and it was fine, so try again now that you have explicitly been given write permissions!

**Comment by EricKeenan** [comment]
Thanks, it worked. I will mark this as closed.
